### PR TITLE
add a defineSignal function for prototype-based signals

### PR DESCRIPTION
**Pull request by sccolbert**
For discussion. Will need to update tests if we like this.

### CODE REVIEW

**Comment by blink1073** [comment]
I like it, I did not like the idea of having the interface definition split in two, this is less boiler plate than the original version, and avoids the `bind()`.  :shipit:

**Comment by sccolbert** [comment]
Well, the allocation is still there, but the boilerplate around it is gone.

**Comment by blink1073** [comment]
But it is one allocation per instance of an empty Object, right?

**Comment by blink1073** [comment]
And only created if needed?

**Comment by sccolbert** [comment]
No: https://github.com/phosphorjs/phosphor-core/pull/45/files#diff-4b03a7c28e330c99135f89854f9c2768R179

**Comment by blink1073** [comment]
Ah, the token is always created, the Signal is created per instance on demand, I see.

**Comment by blink1073** [comment]
No, per access.  Can't it be cached?

**Comment by sccolbert** [comment]
No. Because the caching would be per-instance of the sender. The signal is defined on the prototype, and bound to the `this` on-demand.

**Comment by blink1073** [comment]
Okay, my brain is finally caught up. :+1:

**Comment by sccolbert** [comment]
Tests are updated.

**Pull request merged**
